/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: ceca41d24a60325e358512e6359ae1c9)
interface __BaseEnv_CloudflareBindings {
	DB: D1Database;
	REALTIME_ENABLED: "false";
	AUTH_PROVIDER: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	REALTIME_ROOM: DurableObjectNamespace<import("./src/server").RealtimeRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "RealtimeRoom";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REALTIME_ENABLED" | "AUTH_PROVIDER" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
