/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: cfb5012090907989c2b88ca5619b143d)
interface __BaseEnv_CloudflareBindings {
	FILES: R2Bucket;
	DB: D1Database;
	AUTH_RATE_LIMITER: RateLimit;
	AUTH_PROVIDER: "betterauth";
	R2_ACCOUNT_ID: "";
	R2_BUCKET_NAME: "micropreneur-starter-files";
	REALTIME_ENABLED: "false";
	REALTIME_ROOM: DurableObjectNamespace<import("./src/server").RealtimeRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "RealtimeRoom";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_PROVIDER" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "REALTIME_ENABLED">> {}
}
