/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=DocsBindings` (hash: 5e207eefd0ab9103d790f9337aab5a32)
interface __BaseEnv_DocsBindings {
	ASSETS: Fetcher;
	PUBLIC_DOCS_ORIGIN: "http://localhost:3001";
	ELEMENTS_REGISTRY_URL: "http://localhost:3001/r";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_DocsBindings {}
}
interface DocsBindings extends __BaseEnv_DocsBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_DOCS_ORIGIN" | "ELEMENTS_REGISTRY_URL">> {}
}
