/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiRequestPasswordResetRouteImport } from './routes/api/request-password-reset'
import { Route as ApiResetPasswordRouteImport } from './routes/api/reset-password'
import { Route as ApiSendVerificationRouteImport } from './routes/api/send-verification'
import { Route as ApiSignInRouteImport } from './routes/api/sign-in'
import { Route as ApiSignInSocialRouteImport } from './routes/api/sign-in-social'
import { Route as ApiSignOutRouteImport } from './routes/api/sign-out'
import { Route as ApiSignUpRouteImport } from './routes/api/sign-up'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountEmailRouteImport } from './routes/api/account/email'
import { Route as ApiAccountPasswordRouteImport } from './routes/api/account/password'
import { Route as ApiAccountProfileRouteImport } from './routes/api/account/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiFilesAvatarRouteImport } from './routes/api/files/avatar'
import { Route as ApiFilesCompleteRouteImport } from './routes/api/files/complete'
import { Route as ApiFilesLogoRouteImport } from './routes/api/files/logo'
import { Route as ApiFilesUploadUrlRouteImport } from './routes/api/files/upload-url'
import { Route as ApiRegistryExportRouteImport } from './routes/api/registry/export'
import { Route as AppRegistryIndexRouteImport } from './routes/app.registry.index'
import { Route as AppRegistryRecordIdRouteImport } from './routes/app.registry.$recordId'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSettingsBillingRouteImport } from './routes/app.settings.billing'
import { Route as AppSettingsDangerRouteImport } from './routes/app.settings.danger'
import { Route as AppSettingsProfileRouteImport } from './routes/app.settings.profile'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestPasswordResetRoute = ApiRequestPasswordResetRouteImport.update({
  id: '/api/request-password-reset',
  path: '/api/request-password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetPasswordRoute = ApiResetPasswordRouteImport.update({
  id: '/api/reset-password',
  path: '/api/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendVerificationRoute = ApiSendVerificationRouteImport.update({
  id: '/api/send-verification',
  path: '/api/send-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignInRoute = ApiSignInRouteImport.update({
  id: '/api/sign-in',
  path: '/api/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignInSocialRoute = ApiSignInSocialRouteImport.update({
  id: '/api/sign-in-social',
  path: '/api/sign-in-social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignOutRoute = ApiSignOutRouteImport.update({
  id: '/api/sign-out',
  path: '/api/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignUpRoute = ApiSignUpRouteImport.update({
  id: '/api/sign-up',
  path: '/api/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountEmailRoute = ApiAccountEmailRouteImport.update({
  id: '/api/account/email',
  path: '/api/account/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountPasswordRoute = ApiAccountPasswordRouteImport.update({
  id: '/api/account/password',
  path: '/api/account/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountProfileRoute = ApiAccountProfileRouteImport.update({
  id: '/api/account/profile',
  path: '/api/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesAvatarRoute = ApiFilesAvatarRouteImport.update({
  id: '/api/files/avatar',
  path: '/api/files/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesCompleteRoute = ApiFilesCompleteRouteImport.update({
  id: '/api/files/complete',
  path: '/api/files/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesLogoRoute = ApiFilesLogoRouteImport.update({
  id: '/api/files/logo',
  path: '/api/files/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadUrlRoute = ApiFilesUploadUrlRouteImport.update({
  id: '/api/files/upload-url',
  path: '/api/files/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistryExportRoute = ApiRegistryExportRouteImport.update({
  id: '/api/registry/export',
  path: '/api/registry/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRegistryIndexRoute = AppRegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryRecordIdRoute = AppRegistryRecordIdRouteImport.update({
  id: '/registry/$recordId',
  path: '/registry/$recordId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDangerRoute = AppSettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/request-password-reset': typeof ApiRequestPasswordResetRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/api/send-verification': typeof ApiSendVerificationRoute
  '/api/sign-in': typeof ApiSignInRoute
  '/api/sign-in-social': typeof ApiSignInSocialRoute
  '/api/sign-out': typeof ApiSignOutRoute
  '/api/sign-up': typeof ApiSignUpRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/password': typeof ApiAccountPasswordRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/files/avatar': typeof ApiFilesAvatarRoute
  '/api/files/complete': typeof ApiFilesCompleteRoute
  '/api/files/logo': typeof ApiFilesLogoRoute
  '/api/files/upload-url': typeof ApiFilesUploadUrlRoute
  '/api/registry/export': typeof ApiRegistryExportRoute
  '/app/registry/$recordId': typeof AppRegistryRecordIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/danger': typeof AppSettingsDangerRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/registry/': typeof AppRegistryIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/request-password-reset': typeof ApiRequestPasswordResetRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/api/send-verification': typeof ApiSendVerificationRoute
  '/api/sign-in': typeof ApiSignInRoute
  '/api/sign-in-social': typeof ApiSignInSocialRoute
  '/api/sign-out': typeof ApiSignOutRoute
  '/api/sign-up': typeof ApiSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/password': typeof ApiAccountPasswordRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/files/avatar': typeof ApiFilesAvatarRoute
  '/api/files/complete': typeof ApiFilesCompleteRoute
  '/api/files/logo': typeof ApiFilesLogoRoute
  '/api/files/upload-url': typeof ApiFilesUploadUrlRoute
  '/api/registry/export': typeof ApiRegistryExportRoute
  '/app/registry/$recordId': typeof AppRegistryRecordIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/danger': typeof AppSettingsDangerRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/registry': typeof AppRegistryIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/request-password-reset': typeof ApiRequestPasswordResetRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/api/send-verification': typeof ApiSendVerificationRoute
  '/api/sign-in': typeof ApiSignInRoute
  '/api/sign-in-social': typeof ApiSignInSocialRoute
  '/api/sign-out': typeof ApiSignOutRoute
  '/api/sign-up': typeof ApiSignUpRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/email': typeof ApiAccountEmailRoute
  '/api/account/password': typeof ApiAccountPasswordRoute
  '/api/account/profile': typeof ApiAccountProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/files/avatar': typeof ApiFilesAvatarRoute
  '/api/files/complete': typeof ApiFilesCompleteRoute
  '/api/files/logo': typeof ApiFilesLogoRoute
  '/api/files/upload-url': typeof ApiFilesUploadUrlRoute
  '/api/registry/export': typeof ApiRegistryExportRoute
  '/app/registry/$recordId': typeof AppRegistryRecordIdRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/danger': typeof AppSettingsDangerRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/registry/': typeof AppRegistryIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blog'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/request-password-reset'
    | '/api/reset-password'
    | '/api/send-verification'
    | '/api/sign-in'
    | '/api/sign-in-social'
    | '/api/sign-out'
    | '/api/sign-up'
    | '/app/settings'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/password'
    | '/api/account/profile'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/files/avatar'
    | '/api/files/complete'
    | '/api/files/logo'
    | '/api/files/upload-url'
    | '/api/registry/export'
    | '/app/registry/$recordId'
    | '/app/settings/billing'
    | '/app/settings/danger'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/registry/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/request-password-reset'
    | '/api/reset-password'
    | '/api/send-verification'
    | '/api/sign-in'
    | '/api/sign-in-social'
    | '/api/sign-out'
    | '/api/sign-up'
    | '/blog/$slug'
    | '/app'
    | '/blog'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/password'
    | '/api/account/profile'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/files/avatar'
    | '/api/files/complete'
    | '/api/files/logo'
    | '/api/files/upload-url'
    | '/api/registry/export'
    | '/app/registry/$recordId'
    | '/app/settings/billing'
    | '/app/settings/danger'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/registry'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/blog'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/request-password-reset'
    | '/api/reset-password'
    | '/api/send-verification'
    | '/api/sign-in'
    | '/api/sign-in-social'
    | '/api/sign-out'
    | '/api/sign-up'
    | '/app/settings'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
    | '/api/account/delete'
    | '/api/account/email'
    | '/api/account/password'
    | '/api/account/profile'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/files/avatar'
    | '/api/files/complete'
    | '/api/files/logo'
    | '/api/files/upload-url'
    | '/api/registry/export'
    | '/app/registry/$recordId'
    | '/app/settings/billing'
    | '/app/settings/danger'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/registry/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiRequestPasswordResetRoute: typeof ApiRequestPasswordResetRoute
  ApiResetPasswordRoute: typeof ApiResetPasswordRoute
  ApiSendVerificationRoute: typeof ApiSendVerificationRoute
  ApiSignInRoute: typeof ApiSignInRoute
  ApiSignInSocialRoute: typeof ApiSignInSocialRoute
  ApiSignOutRoute: typeof ApiSignOutRoute
  ApiSignUpRoute: typeof ApiSignUpRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountEmailRoute: typeof ApiAccountEmailRoute
  ApiAccountPasswordRoute: typeof ApiAccountPasswordRoute
  ApiAccountProfileRoute: typeof ApiAccountProfileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiFilesAvatarRoute: typeof ApiFilesAvatarRoute
  ApiFilesCompleteRoute: typeof ApiFilesCompleteRoute
  ApiFilesLogoRoute: typeof ApiFilesLogoRoute
  ApiFilesUploadUrlRoute: typeof ApiFilesUploadUrlRoute
  ApiRegistryExportRoute: typeof ApiRegistryExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-password-reset': {
      id: '/api/request-password-reset'
      path: '/api/request-password-reset'
      fullPath: '/api/request-password-reset'
      preLoaderRoute: typeof ApiRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset-password': {
      id: '/api/reset-password'
      path: '/api/reset-password'
      fullPath: '/api/reset-password'
      preLoaderRoute: typeof ApiResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-verification': {
      id: '/api/send-verification'
      path: '/api/send-verification'
      fullPath: '/api/send-verification'
      preLoaderRoute: typeof ApiSendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sign-in': {
      id: '/api/sign-in'
      path: '/api/sign-in'
      fullPath: '/api/sign-in'
      preLoaderRoute: typeof ApiSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sign-in-social': {
      id: '/api/sign-in-social'
      path: '/api/sign-in-social'
      fullPath: '/api/sign-in-social'
      preLoaderRoute: typeof ApiSignInSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sign-out': {
      id: '/api/sign-out'
      path: '/api/sign-out'
      fullPath: '/api/sign-out'
      preLoaderRoute: typeof ApiSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sign-up': {
      id: '/api/sign-up'
      path: '/api/sign-up'
      fullPath: '/api/sign-up'
      preLoaderRoute: typeof ApiSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/email': {
      id: '/api/account/email'
      path: '/api/account/email'
      fullPath: '/api/account/email'
      preLoaderRoute: typeof ApiAccountEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/password': {
      id: '/api/account/password'
      path: '/api/account/password'
      fullPath: '/api/account/password'
      preLoaderRoute: typeof ApiAccountPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/profile': {
      id: '/api/account/profile'
      path: '/api/account/profile'
      fullPath: '/api/account/profile'
      preLoaderRoute: typeof ApiAccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/avatar': {
      id: '/api/files/avatar'
      path: '/api/files/avatar'
      fullPath: '/api/files/avatar'
      preLoaderRoute: typeof ApiFilesAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/complete': {
      id: '/api/files/complete'
      path: '/api/files/complete'
      fullPath: '/api/files/complete'
      preLoaderRoute: typeof ApiFilesCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/logo': {
      id: '/api/files/logo'
      path: '/api/files/logo'
      fullPath: '/api/files/logo'
      preLoaderRoute: typeof ApiFilesLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload-url': {
      id: '/api/files/upload-url'
      path: '/api/files/upload-url'
      fullPath: '/api/files/upload-url'
      preLoaderRoute: typeof ApiFilesUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registry/export': {
      id: '/api/registry/export'
      path: '/api/registry/export'
      fullPath: '/api/registry/export'
      preLoaderRoute: typeof ApiRegistryExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/registry/': {
      id: '/app/registry/'
      path: '/registry'
      fullPath: '/app/registry/'
      preLoaderRoute: typeof AppRegistryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registry/$recordId': {
      id: '/app/registry/$recordId'
      path: '/registry/$recordId'
      fullPath: '/app/registry/$recordId'
      preLoaderRoute: typeof AppRegistryRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/billing': {
      id: '/app/settings/billing'
      path: '/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/danger': {
      id: '/app/settings/danger'
      path: '/danger'
      fullPath: '/app/settings/danger'
      preLoaderRoute: typeof AppSettingsDangerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsDangerRoute: typeof AppSettingsDangerRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsDangerRoute: AppSettingsDangerRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppRegistryRecordIdRoute: typeof AppRegistryRecordIdRoute
  AppRegistryIndexRoute: typeof AppRegistryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppRegistryRecordIdRoute: AppRegistryRecordIdRoute,
  AppRegistryIndexRoute: AppRegistryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiRequestPasswordResetRoute: ApiRequestPasswordResetRoute,
  ApiResetPasswordRoute: ApiResetPasswordRoute,
  ApiSendVerificationRoute: ApiSendVerificationRoute,
  ApiSignInRoute: ApiSignInRoute,
  ApiSignInSocialRoute: ApiSignInSocialRoute,
  ApiSignOutRoute: ApiSignOutRoute,
  ApiSignUpRoute: ApiSignUpRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountEmailRoute: ApiAccountEmailRoute,
  ApiAccountPasswordRoute: ApiAccountPasswordRoute,
  ApiAccountProfileRoute: ApiAccountProfileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiFilesAvatarRoute: ApiFilesAvatarRoute,
  ApiFilesCompleteRoute: ApiFilesCompleteRoute,
  ApiFilesLogoRoute: ApiFilesLogoRoute,
  ApiFilesUploadUrlRoute: ApiFilesUploadUrlRoute,
  ApiRegistryExportRoute: ApiRegistryExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
